Repository kodiak-packages/ventura, pull requests merged in 2020-08, with the labels that each got.

#86 update error formfield in docs
  src/components/FormField/FormField.mdx
Labels: chore, documentation

#82 Merge CI workflows into 1
  .github/workflows/pipeline.yml
  .github/workflows/push.yml
Labels: chore, devops

#84 Remove console errors in tests
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
Labels: chore

#83 Update radio component docs
  src/components/Radio/Radio.mdx
Labels: bug, documentation

#105 Change hover state condition
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Input/Input.tsx
  src/components/Table/Table.mdx
  src/components/Table/Table.test.tsx
  src/components/Table/TableCell/TableCell.module.css
  src/components/Table/TableRow/TableRow.module.css
  src/components/Table/TableRow/TableRow.tsx
  src/components/TextArea/TextArea.tsx
Labels: bug, chore
