Repository kodiak-packages/ventura, pull requests merged in 2020-04, with the labels that each got.

#2 Close "Setup DocZ integration"
  .eslintrc
  .gitignore
  .prettierrc
  .vscode/settings.json
  README.md
  doczrc.js
  index.js
  package.json
  src/components/Button/Button.mdx
  src/components/Button/Button.module.css
  src/components/Button/Button.tsx
  src/components/index.css
  src/index.mdx
  tsconfig.json
  yarn.lock
Labels: feature

#9 Setup build config for publishing
  .firebase/hosting.LmRvY3ovZGlzdA.cache
  .firebaserc
  .gitignore
  firebase.json
  package.json
  src/components/Anchor/Anchor.mdx
  src/components/Anchor/Anchor.tsx
  src/components/Button/Button.mdx
  src/components/Button/Button.module.css
  src/components/Button/Button.tsx
  src/components/index.css
  src/css.d.ts
  src/index.css
  src/index.ts
  src/theme/colors.css
  src/theme/default.css
  tsconfig.json
  yarn.lock
Labels: chore, devops, feature

#13 Set up testing framework for Ventura
  .gitignore
  package.json
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  yarn.lock
Labels: chore, devops

#18 Workflow for testing, linting, building the docs and compiling the source
  .firebase/hosting.LmRvY3ovZGlzdA.cache
  .firebaserc
  .github/workflows/merge.yml
  .github/workflows/push.yml
  docs/index.html
  doczrc.js
  firebase.json
  package.json
  yarn.lock
Labels: devops

#23 Setup README
  README.md
Labels: chore

#21 Fix merge pipeline
  .github/workflows/merge.yml
  .github/workflows/push.yml
  package.json
  tsconfig.json
Labels: bug, devops

#22 Semantic release setup to NPM
  .github/workflows/merge.yml
  package.json
  yarn.lock
Labels: chore, devops
