Repository kodiak-packages/ventura, pull requests merged in 2020-05, with the labels that each got.

#17 Implement icons
  .gitignore
  README.md
  package.json
  src/components/Anchor/Anchor.mdx
  src/components/Anchor/Anchor.tsx
  src/components/Button/Button.mdx
  src/components/Icon/Icon.mdx
  src/components/Icon/Icon.tsx
  src/css.d.ts
  src/filetypes.d.ts
  src/index.css
  src/index.ts
  src/theme/default.css
  yarn.lock
Labels: feature

#28 Input component
  .editorconfig
  .github/workflows/push.yml
  doczrc.js
  package.json
  src/components/Input/Input.mdx
  src/components/Input/Input.module.css
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.test.tsx.snap
  src/index.css
  src/theme.css
  src/theme/colors.css
  src/theme/default.css
  tsconfig.json
  yarn.lock
Labels: feature

#29 Button component
  README.md
  package.json
  src/components/Button/Button.mdx
  src/components/Button/Button.module.css
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Icon/Icon.mdx
  src/components/Icon/Icon.tsx
  src/components/Input/Input.module.css
  src/components/utils/Spinner/Spinner.module.css
  src/components/utils/Spinner/Spinner.tsx
  src/index.css
  src/theme.css
  yarn.lock
Labels: feature

#33 Coverage status check
  .github/workflows/push.yml
Labels: chore, devops

#32 Updated colors to match Figma
  src/components/Button/Button.module.css
  src/components/Input/Input.mdx
  src/components/Input/Input.module.css
  src/theme.css
Labels: bug, design

#35 Create Radio button
  package.json
  src/components/Button/Button.mdx
  src/components/Button/Button.module.css
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Icon/Icon.tsx
  src/components/Input/Input.mdx
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/components/Input/docAssets/docs.module.css
  src/components/Radio/Radio.mdx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.ts
  src/components/Radio/RadioGroup/RadioGroup.tsx
  src/components/Radio/RadioItem/RadioItem.module.css
  src/components/Radio/RadioItem/RadioItem.tsx
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/Radio/docAssets/docker.png
  src/components/Radio/docAssets/python.png
  src/components/Radio/docAssets/react.png
  src/index.css
  src/index.ts
  src/theme.css
Labels: feature

#43 Remove test files from the package
  package.json
  tsconfig-build.json
  tsconfig.json
Labels: chore, devops

#42 Add codecov
  .github/workflows/push.yml
Labels: devops

#44 Create styleable container around Radio items
  package.json
  src/components/Radio/RadioGroup/RadioGroup.tsx
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
Labels: chore

#48 Change input properties
  src/components/Input/Input.mdx
  src/components/Input/Input.module.css
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
Labels: chore

#41 Apply html and body styles to each component
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.test.tsx.snap
  src/components/Radio/RadioGroup/RadioGroup.tsx
  src/components/Radio/RadioItem/RadioItem.tsx
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/utils/Spinner/Spinner.tsx
  src/css-reset.module.css
  src/index.css
Labels: bug

#49 General component fixes
  src/components/Button/Button.module.css
  src/components/Input/Input.mdx
  src/components/Input/Input.module.css
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.test.tsx.snap
  src/components/Input/docAssets/docs.module.css
  src/components/utils/Spinner/Spinner.module.css
  src/css-reset.module.css
  tsconfig.json
Labels: bug, chore

#51 Modal component
  .prettierignore
  package.json
  src/components/Button/Button.module.css
  src/components/Input/Input.module.css
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.ts
  src/components/Modal/ModalDialog/ModalDialog.module.css
  src/components/Modal/ModalDialog/ModalDialog.tsx
  src/components/Modal/ModalFooter/ModalFooter.module.css
  src/components/Modal/ModalFooter/ModalFooter.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/css-reset.module.css
  src/index.ts
  src/theme.css
  yarn.lock
Labels: feature
